/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookingPolicyRouteImport } from './routes/booking-policy'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as WhyShreyaRouteImport } from './routes/why-shreya'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsDelhiNcrRouteImport } from './routes/locations.delhi-ncr'
import { Route as LocationsGhaziabadRouteImport } from './routes/locations.ghaziabad'
import { Route as LocationsGreaterNoidaRouteImport } from './routes/locations.greater-noida'
import { Route as LocationsMeerutRouteImport } from './routes/locations.meerut'
import { Route as LocationsMuzaffarnagarRouteImport } from './routes/locations.muzaffarnagar'
import { Route as LocationsNoidaRouteImport } from './routes/locations.noida'
import { Route as LocationsShamliRouteImport } from './routes/locations.shamli'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioBridalRouteImport } from './routes/portfolio.bridal'
import { Route as PortfolioEngagementRouteImport } from './routes/portfolio.engagement'
import { Route as PortfolioPartyRouteImport } from './routes/portfolio.party'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPolicyRoute = BookingPolicyRouteImport.update({
  id: '/booking-policy',
  path: '/booking-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyShreyaRoute = WhyShreyaRouteImport.update({
  id: '/why-shreya',
  path: '/why-shreya',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsDelhiNcrRoute = LocationsDelhiNcrRouteImport.update({
  id: '/locations/delhi-ncr',
  path: '/locations/delhi-ncr',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsGhaziabadRoute = LocationsGhaziabadRouteImport.update({
  id: '/locations/ghaziabad',
  path: '/locations/ghaziabad',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsGreaterNoidaRoute = LocationsGreaterNoidaRouteImport.update({
  id: '/locations/greater-noida',
  path: '/locations/greater-noida',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMeerutRoute = LocationsMeerutRouteImport.update({
  id: '/locations/meerut',
  path: '/locations/meerut',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMuzaffarnagarRoute = LocationsMuzaffarnagarRouteImport.update({
  id: '/locations/muzaffarnagar',
  path: '/locations/muzaffarnagar',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsNoidaRoute = LocationsNoidaRouteImport.update({
  id: '/locations/noida',
  path: '/locations/noida',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsShamliRoute = LocationsShamliRouteImport.update({
  id: '/locations/shamli',
  path: '/locations/shamli',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioBridalRoute = PortfolioBridalRouteImport.update({
  id: '/portfolio/bridal',
  path: '/portfolio/bridal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioEngagementRoute = PortfolioEngagementRouteImport.update({
  id: '/portfolio/engagement',
  path: '/portfolio/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioPartyRoute = PortfolioPartyRouteImport.update({
  id: '/portfolio/party',
  path: '/portfolio/party',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/testimonials': typeof TestimonialsRoute
  '/why-shreya': typeof WhyShreyaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/delhi-ncr': typeof LocationsDelhiNcrRoute
  '/locations/ghaziabad': typeof LocationsGhaziabadRoute
  '/locations/greater-noida': typeof LocationsGreaterNoidaRoute
  '/locations/meerut': typeof LocationsMeerutRoute
  '/locations/muzaffarnagar': typeof LocationsMuzaffarnagarRoute
  '/locations/noida': typeof LocationsNoidaRoute
  '/locations/shamli': typeof LocationsShamliRoute
  '/portfolio/bridal': typeof PortfolioBridalRoute
  '/portfolio/engagement': typeof PortfolioEngagementRoute
  '/portfolio/party': typeof PortfolioPartyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/testimonials': typeof TestimonialsRoute
  '/why-shreya': typeof WhyShreyaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/delhi-ncr': typeof LocationsDelhiNcrRoute
  '/locations/ghaziabad': typeof LocationsGhaziabadRoute
  '/locations/greater-noida': typeof LocationsGreaterNoidaRoute
  '/locations/meerut': typeof LocationsMeerutRoute
  '/locations/muzaffarnagar': typeof LocationsMuzaffarnagarRoute
  '/locations/noida': typeof LocationsNoidaRoute
  '/locations/shamli': typeof LocationsShamliRoute
  '/portfolio/bridal': typeof PortfolioBridalRoute
  '/portfolio/engagement': typeof PortfolioEngagementRoute
  '/portfolio/party': typeof PortfolioPartyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/testimonials': typeof TestimonialsRoute
  '/why-shreya': typeof WhyShreyaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/delhi-ncr': typeof LocationsDelhiNcrRoute
  '/locations/ghaziabad': typeof LocationsGhaziabadRoute
  '/locations/greater-noida': typeof LocationsGreaterNoidaRoute
  '/locations/meerut': typeof LocationsMeerutRoute
  '/locations/muzaffarnagar': typeof LocationsMuzaffarnagarRoute
  '/locations/noida': typeof LocationsNoidaRoute
  '/locations/shamli': typeof LocationsShamliRoute
  '/portfolio/bridal': typeof PortfolioBridalRoute
  '/portfolio/engagement': typeof PortfolioEngagementRoute
  '/portfolio/party': typeof PortfolioPartyRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking-policy'
    | '/brands'
    | '/contact'
    | '/packages'
    | '/privacy-policy'
    | '/testimonials'
    | '/why-shreya'
    | '/blog/$slug'
    | '/locations/delhi-ncr'
    | '/locations/ghaziabad'
    | '/locations/greater-noida'
    | '/locations/meerut'
    | '/locations/muzaffarnagar'
    | '/locations/noida'
    | '/locations/shamli'
    | '/portfolio/bridal'
    | '/portfolio/engagement'
    | '/portfolio/party'
    | '/services/$slug'
    | '/blog/'
    | '/locations/'
    | '/portfolio/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking-policy'
    | '/brands'
    | '/contact'
    | '/packages'
    | '/privacy-policy'
    | '/testimonials'
    | '/why-shreya'
    | '/blog/$slug'
    | '/locations/delhi-ncr'
    | '/locations/ghaziabad'
    | '/locations/greater-noida'
    | '/locations/meerut'
    | '/locations/muzaffarnagar'
    | '/locations/noida'
    | '/locations/shamli'
    | '/portfolio/bridal'
    | '/portfolio/engagement'
    | '/portfolio/party'
    | '/services/$slug'
    | '/blog'
    | '/locations'
    | '/portfolio'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking-policy'
    | '/brands'
    | '/contact'
    | '/packages'
    | '/privacy-policy'
    | '/testimonials'
    | '/why-shreya'
    | '/blog/$slug'
    | '/locations/delhi-ncr'
    | '/locations/ghaziabad'
    | '/locations/greater-noida'
    | '/locations/meerut'
    | '/locations/muzaffarnagar'
    | '/locations/noida'
    | '/locations/shamli'
    | '/portfolio/bridal'
    | '/portfolio/engagement'
    | '/portfolio/party'
    | '/services/$slug'
    | '/blog/'
    | '/locations/'
    | '/portfolio/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingPolicyRoute: typeof BookingPolicyRoute
  BrandsRoute: typeof BrandsRoute
  ContactRoute: typeof ContactRoute
  PackagesRoute: typeof PackagesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WhyShreyaRoute: typeof WhyShreyaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LocationsDelhiNcrRoute: typeof LocationsDelhiNcrRoute
  LocationsGhaziabadRoute: typeof LocationsGhaziabadRoute
  LocationsGreaterNoidaRoute: typeof LocationsGreaterNoidaRoute
  LocationsMeerutRoute: typeof LocationsMeerutRoute
  LocationsMuzaffarnagarRoute: typeof LocationsMuzaffarnagarRoute
  LocationsNoidaRoute: typeof LocationsNoidaRoute
  LocationsShamliRoute: typeof LocationsShamliRoute
  PortfolioBridalRoute: typeof PortfolioBridalRoute
  PortfolioEngagementRoute: typeof PortfolioEngagementRoute
  PortfolioPartyRoute: typeof PortfolioPartyRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-policy': {
      id: '/booking-policy'
      path: '/booking-policy'
      fullPath: '/booking-policy'
      preLoaderRoute: typeof BookingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-shreya': {
      id: '/why-shreya'
      path: '/why-shreya'
      fullPath: '/why-shreya'
      preLoaderRoute: typeof WhyShreyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/delhi-ncr': {
      id: '/locations/delhi-ncr'
      path: '/locations/delhi-ncr'
      fullPath: '/locations/delhi-ncr'
      preLoaderRoute: typeof LocationsDelhiNcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/ghaziabad': {
      id: '/locations/ghaziabad'
      path: '/locations/ghaziabad'
      fullPath: '/locations/ghaziabad'
      preLoaderRoute: typeof LocationsGhaziabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/greater-noida': {
      id: '/locations/greater-noida'
      path: '/locations/greater-noida'
      fullPath: '/locations/greater-noida'
      preLoaderRoute: typeof LocationsGreaterNoidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/meerut': {
      id: '/locations/meerut'
      path: '/locations/meerut'
      fullPath: '/locations/meerut'
      preLoaderRoute: typeof LocationsMeerutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/muzaffarnagar': {
      id: '/locations/muzaffarnagar'
      path: '/locations/muzaffarnagar'
      fullPath: '/locations/muzaffarnagar'
      preLoaderRoute: typeof LocationsMuzaffarnagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/noida': {
      id: '/locations/noida'
      path: '/locations/noida'
      fullPath: '/locations/noida'
      preLoaderRoute: typeof LocationsNoidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/shamli': {
      id: '/locations/shamli'
      path: '/locations/shamli'
      fullPath: '/locations/shamli'
      preLoaderRoute: typeof LocationsShamliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/bridal': {
      id: '/portfolio/bridal'
      path: '/portfolio/bridal'
      fullPath: '/portfolio/bridal'
      preLoaderRoute: typeof PortfolioBridalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/engagement': {
      id: '/portfolio/engagement'
      path: '/portfolio/engagement'
      fullPath: '/portfolio/engagement'
      preLoaderRoute: typeof PortfolioEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/party': {
      id: '/portfolio/party'
      path: '/portfolio/party'
      fullPath: '/portfolio/party'
      preLoaderRoute: typeof PortfolioPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingPolicyRoute: BookingPolicyRoute,
  BrandsRoute: BrandsRoute,
  ContactRoute: ContactRoute,
  PackagesRoute: PackagesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TestimonialsRoute: TestimonialsRoute,
  WhyShreyaRoute: WhyShreyaRoute,
  BlogSlugRoute: BlogSlugRoute,
  LocationsDelhiNcrRoute: LocationsDelhiNcrRoute,
  LocationsGhaziabadRoute: LocationsGhaziabadRoute,
  LocationsGreaterNoidaRoute: LocationsGreaterNoidaRoute,
  LocationsMeerutRoute: LocationsMeerutRoute,
  LocationsMuzaffarnagarRoute: LocationsMuzaffarnagarRoute,
  LocationsNoidaRoute: LocationsNoidaRoute,
  LocationsShamliRoute: LocationsShamliRoute,
  PortfolioBridalRoute: PortfolioBridalRoute,
  PortfolioEngagementRoute: PortfolioEngagementRoute,
  PortfolioPartyRoute: PortfolioPartyRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
